services:
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"
    volumes:
      - ./data/valkey:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 3 &&
      ollama pull tinyllama &&
      ollama pull nomic-embed-text &&
      tail -f /dev/null
      "

volumes:
  ollama_data:
